apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ride-sharing
spec:
  accessModes:
    - ReadWriteOnce # Suitable for a single pod
  resources:
    requests:
      storage: 1Gi # Adjust storage size as needed
  # Optional: Specify a storageClassName if needed for your cluster
  # storageClassName: standard 