apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ride-sharing
spec:
  selector:
    app: postgres # Selects the pods managed by the StatefulSet
  ports:
    - protocol: TCP
      port: 5432 # Port the service listens on
      targetPort: 5432 # Port the container listens on
  type: ClusterIP # Exposes the service only within the cluster 