apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ride-sharing
type: Opaque
data:
  # Use base64 encoded values
  # Example: echo -n 'yourpassword' | base64
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded "postgres"
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 encoded "password" - CHANGE THIS!
  POSTGRES_DB: aG1zX2Ri # base64 encoded "hms_db" 