// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/staff-service/staff.proto

package staff_service

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaffRoleProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffRoleProto) Reset() {
	*x = StaffRoleProto{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffRoleProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffRoleProto) ProtoMessage() {}

func (x *StaffRoleProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffRoleProto.ProtoReflect.Descriptor instead.
func (*StaffRoleProto) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{0}
}

func (x *StaffRoleProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffRoleProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StaffStatusProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffStatusProto) Reset() {
	*x = StaffStatusProto{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffStatusProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffStatusProto) ProtoMessage() {}

func (x *StaffStatusProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffStatusProto.ProtoReflect.Descriptor instead.
func (*StaffStatusProto) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{1}
}

func (x *StaffStatusProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffStatusProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TaskStatusProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusProto) Reset() {
	*x = TaskStatusProto{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusProto) ProtoMessage() {}

func (x *TaskStatusProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusProto.ProtoReflect.Descriptor instead.
func (*TaskStatusProto) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStatusProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskStatusProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Corresponds to entity.Task
type TaskProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	StatusId      string                 `protobuf:"bytes,7,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProto) Reset() {
	*x = TaskProto{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProto) ProtoMessage() {}

func (x *TaskProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProto.ProtoReflect.Descriptor instead.
func (*TaskProto) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{3}
}

func (x *TaskProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskProto) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskProto) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TaskProto) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TaskProto) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *TaskProto) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TaskProto) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Corresponds to entity.ScheduleEntry (Join Table)
type ScheduleEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Task          *TaskProto             `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEntryProto) Reset() {
	*x = ScheduleEntryProto{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEntryProto) ProtoMessage() {}

func (x *ScheduleEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEntryProto.ProtoReflect.Descriptor instead.
func (*ScheduleEntryProto) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleEntryProto) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *ScheduleEntryProto) GetTask() *TaskProto {
	if x != nil {
		return x.Task
	}
	return nil
}

// Corresponds to entity.Staff
type Staff struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	PhoneNumber    string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address        string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	RoleId         string                 `protobuf:"bytes,7,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	StatusId       string                 `protobuf:"bytes,8,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	Specialization string                 `protobuf:"bytes,9,opt,name=specialization,proto3" json:"specialization,omitempty"`
	NurseType      string                 `protobuf:"bytes,10,opt,name=nurse_type,json=nurseType,proto3" json:"nurse_type,omitempty"`
	Schedule       []*ScheduleEntryProto  `protobuf:"bytes,11,rep,name=schedule,proto3" json:"schedule,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{5}
}

func (x *Staff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Staff) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Staff) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Staff) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *Staff) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Staff) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Staff) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Staff) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *Staff) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *Staff) GetNurseType() string {
	if x != nil {
		return x.NurseType
	}
	return ""
}

func (x *Staff) GetSchedule() []*ScheduleEntryProto {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *Staff) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Staff) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Staff Operations
type AddStaffRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstName      string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	PhoneNumber    string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address        string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	RoleId         string                 `protobuf:"bytes,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	StatusId       string                 `protobuf:"bytes,7,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	Specialization string                 `protobuf:"bytes,8,opt,name=specialization,proto3" json:"specialization,omitempty"`
	NurseType      string                 `protobuf:"bytes,9,opt,name=nurse_type,json=nurseType,proto3" json:"nurse_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddStaffRequest) Reset() {
	*x = AddStaffRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffRequest) ProtoMessage() {}

func (x *AddStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffRequest.ProtoReflect.Descriptor instead.
func (*AddStaffRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{6}
}

func (x *AddStaffRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AddStaffRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AddStaffRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *AddStaffRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *AddStaffRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddStaffRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AddStaffRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *AddStaffRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *AddStaffRequest) GetNurseType() string {
	if x != nil {
		return x.NurseType
	}
	return ""
}

type AddStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStaffResponse) Reset() {
	*x = AddStaffResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffResponse) ProtoMessage() {}

func (x *AddStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffResponse.ProtoReflect.Descriptor instead.
func (*AddStaffResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{7}
}

func (x *AddStaffResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type GetStaffDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffDetailsRequest) Reset() {
	*x = GetStaffDetailsRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffDetailsRequest) ProtoMessage() {}

func (x *GetStaffDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetStaffDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{8}
}

func (x *GetStaffDetailsRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type GetStaffDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffDetailsResponse) Reset() {
	*x = GetStaffDetailsResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffDetailsResponse) ProtoMessage() {}

func (x *GetStaffDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetStaffDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{9}
}

func (x *GetStaffDetailsResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type UpdateStaffDetailsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	StaffId string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	// Fields below are optional for update (use wrappers or field masks in real app)
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	PhoneNumber    string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address        string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Specialization string                 `protobuf:"bytes,7,opt,name=specialization,proto3" json:"specialization,omitempty"`
	NurseType      string                 `protobuf:"bytes,8,opt,name=nurse_type,json=nurseType,proto3" json:"nurse_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStaffDetailsRequest) Reset() {
	*x = UpdateStaffDetailsRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffDetailsRequest) ProtoMessage() {}

func (x *UpdateStaffDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateStaffDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStaffDetailsRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *UpdateStaffDetailsRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateStaffDetailsRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateStaffDetailsRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateStaffDetailsRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateStaffDetailsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateStaffDetailsRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *UpdateStaffDetailsRequest) GetNurseType() string {
	if x != nil {
		return x.NurseType
	}
	return ""
}

type UpdateStaffDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaffDetailsResponse) Reset() {
	*x = UpdateStaffDetailsResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffDetailsResponse) ProtoMessage() {}

func (x *UpdateStaffDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateStaffDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStaffDetailsResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

// Request for ListStaff
type ListStaffRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filtering parameters
	RoleId        string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	StatusId      string `protobuf:"bytes,2,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"` // Add pagination fields like page_size, page_token if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffRequest) Reset() {
	*x = ListStaffRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffRequest) ProtoMessage() {}

func (x *ListStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffRequest.ProtoReflect.Descriptor instead.
func (*ListStaffRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{12}
}

func (x *ListStaffRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *ListStaffRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

// Response for ListStaff
type ListStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffMembers  []*Staff               `protobuf:"bytes,1,rep,name=staff_members,json=staffMembers,proto3" json:"staff_members,omitempty"` // Renamed from 'staff' to avoid conflict
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffResponse) Reset() {
	*x = ListStaffResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffResponse) ProtoMessage() {}

func (x *ListStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffResponse.ProtoReflect.Descriptor instead.
func (*ListStaffResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{13}
}

func (x *ListStaffResponse) GetStaffMembers() []*Staff {
	if x != nil {
		return x.StaffMembers
	}
	return nil
}

type UpdateStaffScheduleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StaffId         string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	TasksToSchedule []*TaskProto           `protobuf:"bytes,2,rep,name=tasks_to_schedule,json=tasksToSchedule,proto3" json:"tasks_to_schedule,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateStaffScheduleRequest) Reset() {
	*x = UpdateStaffScheduleRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffScheduleRequest) ProtoMessage() {}

func (x *UpdateStaffScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpdateStaffScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateStaffScheduleRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *UpdateStaffScheduleRequest) GetTasksToSchedule() []*TaskProto {
	if x != nil {
		return x.TasksToSchedule
	}
	return nil
}

type SetStaffAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	StatusId      string                 `protobuf:"bytes,2,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStaffAvailabilityRequest) Reset() {
	*x = SetStaffAvailabilityRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStaffAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStaffAvailabilityRequest) ProtoMessage() {}

func (x *SetStaffAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStaffAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*SetStaffAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{15}
}

func (x *SetStaffAvailabilityRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *SetStaffAvailabilityRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

type GetDoctorAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorAvailabilityRequest) Reset() {
	*x = GetDoctorAvailabilityRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorAvailabilityRequest) ProtoMessage() {}

func (x *GetDoctorAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{16}
}

func (x *GetDoctorAvailabilityRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *GetDoctorAvailabilityRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetDoctorAvailabilityRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetDoctorAvailabilityResponse struct {
	state          protoimpl.MessageState                    `protogen:"open.v1"`
	AvailableSlots []*GetDoctorAvailabilityResponse_TimeSlot `protobuf:"bytes,1,rep,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDoctorAvailabilityResponse) Reset() {
	*x = GetDoctorAvailabilityResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorAvailabilityResponse) ProtoMessage() {}

func (x *GetDoctorAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{17}
}

func (x *GetDoctorAvailabilityResponse) GetAvailableSlots() []*GetDoctorAvailabilityResponse_TimeSlot {
	if x != nil {
		return x.AvailableSlots
	}
	return nil
}

type AssignTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	StatusId      string                 `protobuf:"bytes,7,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskRequest) Reset() {
	*x = AssignTaskRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskRequest) ProtoMessage() {}

func (x *AssignTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{18}
}

func (x *AssignTaskRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *AssignTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AssignTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AssignTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AssignTaskRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AssignTaskRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *AssignTaskRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

type TrackWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackWorkloadRequest) Reset() {
	*x = TrackWorkloadRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackWorkloadRequest) ProtoMessage() {}

func (x *TrackWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackWorkloadRequest.ProtoReflect.Descriptor instead.
func (*TrackWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{19}
}

func (x *TrackWorkloadRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type TrackWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      []*TaskProto           `protobuf:"bytes,1,rep,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackWorkloadResponse) Reset() {
	*x = TrackWorkloadResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackWorkloadResponse) ProtoMessage() {}

func (x *TrackWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackWorkloadResponse.ProtoReflect.Descriptor instead.
func (*TrackWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{20}
}

func (x *TrackWorkloadResponse) GetWorkload() []*TaskProto {
	if x != nil {
		return x.Workload
	}
	return nil
}

// Request for ListTasks
type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filtering parameters (examples)
	StatusId      string `protobuf:"bytes,1,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{21}
}

func (x *ListTasksRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

// Response for ListTasks
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskProto           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"` // Add pagination fields like next_page_token if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{22}
}

func (x *ListTasksResponse) GetTasks() []*TaskProto {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// Role Operations
type AddStaffRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStaffRoleRequest) Reset() {
	*x = AddStaffRoleRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStaffRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffRoleRequest) ProtoMessage() {}

func (x *AddStaffRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffRoleRequest.ProtoReflect.Descriptor instead.
func (*AddStaffRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{23}
}

func (x *AddStaffRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddStaffRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddStaffRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *StaffRoleProto        `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStaffRoleResponse) Reset() {
	*x = AddStaffRoleResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStaffRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffRoleResponse) ProtoMessage() {}

func (x *AddStaffRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffRoleResponse.ProtoReflect.Descriptor instead.
func (*AddStaffRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{24}
}

func (x *AddStaffRoleResponse) GetRole() *StaffRoleProto {
	if x != nil {
		return x.Role
	}
	return nil
}

type ListStaffRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffRolesRequest) Reset() {
	*x = ListStaffRolesRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffRolesRequest) ProtoMessage() {}

func (x *ListStaffRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffRolesRequest.ProtoReflect.Descriptor instead.
func (*ListStaffRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{25}
}

type ListStaffRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*StaffRoleProto      `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffRolesResponse) Reset() {
	*x = ListStaffRolesResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffRolesResponse) ProtoMessage() {}

func (x *ListStaffRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffRolesResponse.ProtoReflect.Descriptor instead.
func (*ListStaffRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{26}
}

func (x *ListStaffRolesResponse) GetRoles() []*StaffRoleProto {
	if x != nil {
		return x.Roles
	}
	return nil
}

// Status Operations
type AddStaffStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStaffStatusRequest) Reset() {
	*x = AddStaffStatusRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStaffStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffStatusRequest) ProtoMessage() {}

func (x *AddStaffStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffStatusRequest.ProtoReflect.Descriptor instead.
func (*AddStaffStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{27}
}

func (x *AddStaffStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddStaffStatusRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddStaffStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StaffStatusProto      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStaffStatusResponse) Reset() {
	*x = AddStaffStatusResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStaffStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffStatusResponse) ProtoMessage() {}

func (x *AddStaffStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffStatusResponse.ProtoReflect.Descriptor instead.
func (*AddStaffStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{28}
}

func (x *AddStaffStatusResponse) GetStatus() *StaffStatusProto {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListStaffStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffStatusesRequest) Reset() {
	*x = ListStaffStatusesRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffStatusesRequest) ProtoMessage() {}

func (x *ListStaffStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffStatusesRequest.ProtoReflect.Descriptor instead.
func (*ListStaffStatusesRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{29}
}

type ListStaffStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*StaffStatusProto    `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffStatusesResponse) Reset() {
	*x = ListStaffStatusesResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffStatusesResponse) ProtoMessage() {}

func (x *ListStaffStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffStatusesResponse.ProtoReflect.Descriptor instead.
func (*ListStaffStatusesResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{30}
}

func (x *ListStaffStatusesResponse) GetStatuses() []*StaffStatusProto {
	if x != nil {
		return x.Statuses
	}
	return nil
}

// Task Status Operations
type AddTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskStatusRequest) Reset() {
	*x = AddTaskStatusRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskStatusRequest) ProtoMessage() {}

func (x *AddTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*AddTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{31}
}

func (x *AddTaskStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTaskStatusRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *TaskStatusProto       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskStatusResponse) Reset() {
	*x = AddTaskStatusResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskStatusResponse) ProtoMessage() {}

func (x *AddTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*AddTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{32}
}

func (x *AddTaskStatusResponse) GetStatus() *TaskStatusProto {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListTaskStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskStatusesRequest) Reset() {
	*x = ListTaskStatusesRequest{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskStatusesRequest) ProtoMessage() {}

func (x *ListTaskStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskStatusesRequest.ProtoReflect.Descriptor instead.
func (*ListTaskStatusesRequest) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{33}
}

type ListTaskStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TaskStatusProto     `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskStatusesResponse) Reset() {
	*x = ListTaskStatusesResponse{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskStatusesResponse) ProtoMessage() {}

func (x *ListTaskStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskStatusesResponse.ProtoReflect.Descriptor instead.
func (*ListTaskStatusesResponse) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{34}
}

func (x *ListTaskStatusesResponse) GetStatuses() []*TaskStatusProto {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GetDoctorAvailabilityResponse_TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorAvailabilityResponse_TimeSlot) Reset() {
	*x = GetDoctorAvailabilityResponse_TimeSlot{}
	mi := &file_proto_staff_service_staff_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorAvailabilityResponse_TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorAvailabilityResponse_TimeSlot) ProtoMessage() {}

func (x *GetDoctorAvailabilityResponse_TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_staff_service_staff_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorAvailabilityResponse_TimeSlot.ProtoReflect.Descriptor instead.
func (*GetDoctorAvailabilityResponse_TimeSlot) Descriptor() ([]byte, []int) {
	return file_proto_staff_service_staff_proto_rawDescGZIP(), []int{17, 0}
}

func (x *GetDoctorAvailabilityResponse_TimeSlot) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetDoctorAvailabilityResponse_TimeSlot) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

var File_proto_staff_service_staff_proto protoreflect.FileDescriptor

const file_proto_staff_service_staff_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/staff-service/staff.proto\x12\fstaffservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xc6\x02\n" +
	"\x0eStaffRoleProto\x12J\n" +
	"\x04name\x18\x01 \x01(\tB6\x92A32'Unique name for the role (Primary Key).J\b\"Doctor\"R\x04name\x12\x8b\x01\n" +
	"\vdescription\x18\x02 \x01(\tBi\x92Af2!Optional description of the role.JA\"Medical doctor responsible for patient diagnosis and treatment.\"R\vdescription:Z\x92AW\n" +
	"U*\n" +
	"Staff Role2@Represents a role a staff member can have (e.g., Doctor, Nurse).\xd2\x01\x04name\"\xb8\x02\n" +
	"\x10StaffStatusProto\x12L\n" +
	"\x04name\x18\x01 \x01(\tB8\x92A52)Unique name for the status (Primary Key).J\b\"Active\"R\x04name\x12m\n" +
	"\vdescription\x18\x02 \x01(\tBK\x92AH2#Optional description of the status.J!\"Currently employed and working.\"R\vdescription:g\x92Ad\n" +
	"b*\fStaff Status2KRepresents the employment status of a staff member (e.g., Active, OnLeave).\xd2\x01\x04name\"\xc1\x02\n" +
	"\x0fTaskStatusProto\x12R\n" +
	"\x04name\x18\x01 \x01(\tB>\x92A;2.Unique name for the task status (Primary Key).J\t\"Pending\"R\x04name\x12x\n" +
	"\vdescription\x18\x02 \x01(\tBV\x92AS2(Optional description of the task status.J'\"Task is assigned but not yet started.\"R\vdescription:`\x92A]\n" +
	"[*\vTask Status2ERepresents the status of an assigned task (e.g., Pending, Completed).\xd2\x01\x04name\"\x98\n" +
	"\n" +
	"\tTaskProto\x12o\n" +
	"\x02id\x18\x01 \x01(\tB_\x92A\\2-Unique identifier for the task (UUID format).J+\"task-a1b2c3d4-e5f6-7890-1234-567890abcdef\"R\x02id\x12M\n" +
	"\x05title\x18\x02 \x01(\tB7\x92A42\x1aTitle or name of the task.J\x16\"Review Patient Chart\"R\x05title\x12\x89\x01\n" +
	"\vdescription\x18\x03 \x01(\tBg\x92Ad2,Detailed description of the task (optional).J4\"Review Alice Smith's chart before her appointment.\"R\vdescription\x12U\n" +
	"\bpriority\x18\x04 \x01(\x05B9\x92A621Priority level of the task (e.g., 1=High, 5=Low).J\x012R\bpriority\x12\x8e\x01\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampBS\x92AP26Scheduled start time of the task (RFC3339 UTC format).J\x16\"2023-04-01T09:00:00Z\"R\tstartTime\x12\x88\x01\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampBQ\x92AN24Scheduled end time of the task (RFC3339 UTC format).J\x16\"2023-04-01T09:30:00Z\"R\aendTime\x12w\n" +
	"\tstatus_id\x18\a \x01(\tBZ\x92AW2JIdentifier of the task's current status (references TaskStatusProto.name).J\t\"Pending\"R\bstatusId\x12\x91\x01\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampBV\x92AS29Timestamp when the task was created (RFC3339 UTC format).J\x16\"2023-03-30T11:00:00Z\"R\tcreatedAt\x12\x96\x01\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB[\x92AX2>Timestamp when the task was last updated (RFC3339 UTC format).J\x16\"2023-03-30T11:00:00Z\"R\tupdatedAt:\xa5\x01\x92A\xa1\x01\n" +
	"\x9e\x01*\x04Task2@Represents a task assigned to a staff member via their schedule.\xd2\x01\x02id\xd2\x01\x05title\xd2\x01\bpriority\xd2\x01\n" +
	"start_time\xd2\x01\bend_time\xd2\x01\tstatus_id\xd2\x01\n" +
	"created_at\xd2\x01\n" +
	"updated_at\"\xd1\x02\n" +
	"\x12ScheduleEntryProto\x12u\n" +
	"\bstaff_id\x18\x01 \x01(\tBZ\x92AW2-Identifier of the staff member (UUID format).J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\astaffId\x12_\n" +
	"\x04task\x18\x02 \x01(\v2\x17.staffservice.TaskProtoB2\x92A/2-The task associated with this schedule entry.R\x04task:c\x92A`\n" +
	"^*\x0eSchedule Entry2:Links a staff member to a specific task in their schedule.\xd2\x01\bstaff_id\xd2\x01\x04task\"\xbd\r\n" +
	"\x05Staff\x12r\n" +
	"\x02id\x18\x01 \x01(\tBb\x92A_25Unique identifier for the staff member (UUID format).J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\x02id\x12L\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tB-\x92A*2\x1aStaff member's first name.J\f\"Dr. Evelyn\"R\tfirstName\x12C\n" +
	"\tlast_name\x18\x03 \x01(\tB&\x92A#2\x19Staff member's last name.J\x06\"Reed\"R\blastName\x12\x8f\x01\n" +
	"\rdate_of_birth\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBO\x92AL22Staff member's date of birth (RFC3339 UTC format).J\x16\"1980-08-25T00:00:00Z\"R\vdateOfBirth\x12\\\n" +
	"\fphone_number\x18\x05 \x01(\tB9\x92A62$Staff member's contact phone number.J\x0e\"+15550101010\"R\vphoneNumber\x12O\n" +
	"\aaddress\x18\x06 \x01(\tB5\x92A22\x17Staff member's address.J\x17\"789 Staff St, Medtown\"R\aaddress\x12o\n" +
	"\arole_id\x18\a \x01(\tBV\x92AS2GIdentifier of the staff member's role (references StaffRoleProto.name).J\b\"Doctor\"R\x06roleId\x12\x7f\n" +
	"\tstatus_id\x18\b \x01(\tBb\x92A_2SIdentifier of the staff member's current status (references StaffStatusProto.name).J\b\"Active\"R\bstatusId\x12\xa2\x01\n" +
	"\x0especialization\x18\t \x01(\tBz\x92Aw2gThe doctor's area of medical specialization (e.g., \"Cardiology\", \"Neurology\", \"Pediatrics\") (optional).J\f\"Cardiology\"R\x0especialization\x12k\n" +
	"\n" +
	"nurse_type\x18\n" +
	" \x01(\tBL\x92AI2ASpecifies the type of nurse (e.g., \"RN\", \"LPN\", \"NP\") (optional).J\x04\"RN\"R\tnurseType\x12~\n" +
	"\bschedule\x18\v \x03(\v2 .staffservice.ScheduleEntryProtoB@\x92A=2;List of schedule entries, each containing an assigned task.R\bschedule\x12\x99\x01\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB^\x92A[2ATimestamp when the staff record was created (RFC3339 UTC format).J\x16\"2022-11-01T10:00:00Z\"R\tcreatedAt\x12\x9e\x01\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampBc\x92A`2FTimestamp when the staff record was last updated (RFC3339 UTC format).J\x16\"2023-03-15T16:00:00Z\"R\tupdatedAt:\xaa\x01\x92A\xa6\x01\n" +
	"\xa3\x01*\x05Staff2#Represents a hospital staff member.\xd2\x01\x02id\xd2\x01\n" +
	"first_name\xd2\x01\tlast_name\xd2\x01\rdate_of_birth\xd2\x01\fphone_number\xd2\x01\aaddress\xd2\x01\arole_id\xd2\x01\tstatus_id\xd2\x01\n" +
	"created_at\xd2\x01\n" +
	"updated_at\"\xb5\b\n" +
	"\x0fAddStaffRequest\x12K\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tB,\x92A)2\x1aStaff member's first name.J\v\"Nurse Ben\"R\tfirstName\x12E\n" +
	"\tlast_name\x18\x02 \x01(\tB(\x92A%2\x19Staff member's last name.J\b\"Carter\"R\blastName\x12\x80\x01\n" +
	"\rdate_of_birth\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB@\x92A=2#Date of birth (RFC3339 UTC format).J\x16\"1992-03-10T00:00:00Z\"R\vdateOfBirth\x12M\n" +
	"\fphone_number\x18\x04 \x01(\tB*\x92A'2\x15Contact phone number.J\x0e\"+15550202020\"R\vphoneNumber\x12E\n" +
	"\aaddress\x18\x05 \x01(\tB+\x92A(2\bAddress.J\x1c\"101 Nurse Station, Medtown\"R\aaddress\x12s\n" +
	"\arole_id\x18\x06 \x01(\tBZ\x92AW2LRole identifier (e.g., \"Nurse\"). Must match an existing StaffRoleProto.name.J\a\"Nurse\"R\x06roleId\x12}\n" +
	"\tstatus_id\x18\a \x01(\tB`\x92A]2QStatus identifier (e.g., \"Active\"). Must match an existing StaffStatusProto.name.J\b\"Active\"R\bstatusId\x12|\n" +
	"\x0especialization\x18\b \x01(\tBT\x92AQ2ARequired for Doctor role (e.g., \"Neurology\"). Optional otherwise.J\f\"Pediatrics\"R\x0especialization\x12d\n" +
	"\n" +
	"nurse_type\x18\t \x01(\tBE\x92AB29Required for Nurse role (e.g., \"RN\"). Optional otherwise.J\x05\"LPN\"R\tnurseType:\x9c\x01\x92A\x98\x01\n" +
	"\x95\x01*\x11Add Staff Request2(Data required to add a new staff member.\xd2\x01\n" +
	"first_name\xd2\x01\tlast_name\xd2\x01\rdate_of_birth\xd2\x01\fphone_number\xd2\x01\aaddress\xd2\x01\arole_id\xd2\x01\tstatus_id\"\x8f\x01\n" +
	"\x10AddStaffResponse\x12)\n" +
	"\x05staff\x18\x01 \x01(\v2\x13.staffservice.StaffR\x05staff:P\x92AM\n" +
	"K*\x12Add Staff Response25Contains the details of the newly added staff member.\"\xd4\x01\n" +
	"\x16GetStaffDetailsRequest\x12e\n" +
	"\bstaff_id\x18\x01 \x01(\tBJ\x92AG2\x1dThe UUID of the staff member.J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\astaffId:S\x92AP\n" +
	"N*\x19Get Staff Details Request21Specifies the ID of the staff member to retrieve.\"\xbc\x01\n" +
	"\x17GetStaffDetailsResponse\x12)\n" +
	"\x05staff\x18\x01 \x01(\v2\x13.staffservice.StaffR\x05staff:v\x92As\n" +
	"q*\x1aGet Staff Details Response2SContains the details of the requested staff member, including their schedule/tasks.\"\xbd\a\n" +
	"\x19UpdateStaffDetailsRequest\x12o\n" +
	"\bstaff_id\x18\x01 \x01(\tBT\x92AQ2'The UUID of the staff member to update.J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\astaffId\x12J\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tB+\x92A(2\x1aNew first name (optional).J\n" +
	"\"Benjamin\"R\tfirstName\x12E\n" +
	"\tlast_name\x18\x03 \x01(\tB(\x92A%2\x19New last name (optional).J\b\"Carter\"R\blastName\x12\x8e\x01\n" +
	"\rdate_of_birth\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampBN\x92AK21New date of birth (optional, RFC3339 UTC format).J\x16\"1992-03-10T00:00:00Z\"R\vdateOfBirth\x12T\n" +
	"\fphone_number\x18\x05 \x01(\tB1\x92A.2\x1cNew phone number (optional).J\x0e\"+15550202021\"R\vphoneNumber\x12T\n" +
	"\aaddress\x18\x06 \x01(\tB:\x92A72\x17New address (optional).J\x1c\"102 Nurse Station, Medtown\"R\aaddress\x12q\n" +
	"\x0especialization\x18\a \x01(\tBI\x92AF26Updated specialization (optional, mainly for Doctors).J\f\"Cardiology\"R\x0especialization\x12[\n" +
	"\n" +
	"nurse_type\x18\b \x01(\tB<\x92A921Updated nurse type (optional, mainly for Nurses).J\x04\"RN\"R\tnurseType:\x8e\x01\x92A\x8a\x01\n" +
	"\x87\x01*\x1cUpdate Staff Details Request2\\Data for updating an existing staff member. Only include fields to change (PATCH semantics).\xd2\x01\bstaff_id\"\x99\x01\n" +
	"\x1aUpdateStaffDetailsResponse\x12)\n" +
	"\x05staff\x18\x01 \x01(\v2\x13.staffservice.StaffR\x05staff:P\x92AM\n" +
	"K*\x1dUpdate Staff Details Response2*Contains the updated staff member details.\"\xb5\x02\n" +
	"\x10ListStaffRequest\x12U\n" +
	"\arole_id\x18\x01 \x01(\tB<\x92A92-Optional: Filter by role ID (e.g., \"Doctor\").J\b\"Doctor\"R\x06roleId\x12[\n" +
	"\tstatus_id\x18\x02 \x01(\tB>\x92A;2/Optional: Filter by status ID (e.g., \"Active\").J\b\"Active\"R\bstatusId:m\x92Aj\n" +
	"h*\x12List Staff Request2RRequest to list all staff members (add pagination/filtering parameters if needed).\"\xa2\x01\n" +
	"\x11ListStaffResponse\x128\n" +
	"\rstaff_members\x18\x01 \x03(\v2\x13.staffservice.StaffR\fstaffMembers:S\x92AP\n" +
	"N*\x13List Staff Response27Contains a list of staff members matching the criteria.\"\xa0\x03\n" +
	"\x1aUpdateStaffScheduleRequest\x12\x85\x01\n" +
	"\bstaff_id\x18\x01 \x01(\tBj\x92Ag2=The UUID of the staff member whose schedule is being updated.J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\astaffId\x12\x86\x01\n" +
	"\x11tasks_to_schedule\x18\x02 \x03(\v2\x17.staffservice.TaskProtoBA\x92A>2<A list of new tasks to be created and added to the schedule.R\x0ftasksToSchedule:q\x92An\n" +
	"l*\x1dUpdate Staff Schedule Request2,Adds new tasks to a staff member's schedule.\xd2\x01\bstaff_id\xd2\x01\x11tasks_to_schedule\"\xfa\x02\n" +
	"\x1bSetStaffAvailabilityRequest\x12e\n" +
	"\bstaff_id\x18\x01 \x01(\tBJ\x92AG2\x1dThe UUID of the staff member.J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\astaffId\x12\x8b\x01\n" +
	"\tstatus_id\x18\x02 \x01(\tBn\x92Ak2^The name of the target status (e.g., \"OnLeave\"). Must match an existing StaffStatusProto.name.J\t\"OnLeave\"R\bstatusId:f\x92Ac\n" +
	"a*\x18Set Staff Status Request2.Sets the employment status for a staff member.\xd2\x01\bstaff_id\xd2\x01\tstatus_id\"\xd1\x04\n" +
	"\x1cGetDoctorAvailabilityRequest\x12\x92\x01\n" +
	"\tdoctor_id\x18\x01 \x01(\tBu\x92Ar2HOptional: The UUID of a specific doctor. If omitted, checks all doctors.J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\bdoctorId\x12\x85\x01\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampBJ\x92AG2-Start of the time range (RFC3339 UTC format).J\x16\"2023-04-01T08:00:00Z\"R\tstartTime\x12\x7f\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampBH\x92AE2+End of the time range (RFC3339 UTC format).J\x16\"2023-04-01T17:00:00Z\"R\aendTime:\x92\x01\x92A\x8e\x01\n" +
	"\x8b\x01*\x1fGet Doctor Availability Request2PChecks the availability of a specific doctor or all doctors within a time range.\xd2\x01\n" +
	"start_time\xd2\x01\bend_time\"\x85\x05\n" +
	"\x1dGetDoctorAvailabilityResponse\x12\x81\x01\n" +
	"\x0favailable_slots\x18\x01 \x03(\v24.staffservice.GetDoctorAvailabilityResponse.TimeSlotB\"\x92A\x1f2\x1dList of available time slots.R\x0eavailableSlots\x1a\xf4\x02\n" +
	"\bTimeSlot\x12\x8e\x01\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampBS\x92AP26Start time of the available slot (RFC3339 UTC format).J\x16\"2023-04-01T10:00:00Z\"R\tstartTime\x12\x88\x01\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampBQ\x92AN24End time of the available slot (RFC3339 UTC format).J\x16\"2023-04-01T10:30:00Z\"R\aendTime:L\x92AI\n" +
	"G*\x13Available Time Slot20Represents a continuous block of available time.:i\x92Af\n" +
	"d* Get Doctor Availability Response2@A list of time slots when the specified doctor(s) are available.\"\xf4\a\n" +
	"\x11AssignTaskRequest\x12{\n" +
	"\bstaff_id\x18\x01 \x01(\tB`\x92A]23The UUID of the staff member to assign the task to.J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\astaffId\x12E\n" +
	"\x05title\x18\x02 \x01(\tB/\x92A,2\x12Title of the task.J\x16\"Prepare Morning Meds\"R\x05title\x12w\n" +
	"\vdescription\x18\x03 \x01(\tBU\x92AR2!Optional description of the task.J-\"Prepare medications for patients on Ward C.\"R\vdescription\x12a\n" +
	"\bpriority\x18\x04 \x01(\x05BE\x92AB2=Priority level (optional, default depends on implementation).J\x013R\bpriority\x12\x8f\x01\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampBT\x92AQ27Scheduled start time for the task (RFC3339 UTC format).J\x16\"2023-04-01T08:00:00Z\"R\tstartTime\x12\x89\x01\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampBR\x92AO25Scheduled end time for the task (RFC3339 UTC format).J\x16\"2023-04-01T08:30:00Z\"R\aendTime\x12\x88\x01\n" +
	"\tstatus_id\x18\a \x01(\tBk\x92Ah2[Initial status for the task (e.g., \"Pending\"). Must match an existing TaskStatusProto.name.J\t\"Pending\"R\bstatusId:\x95\x01\x92A\x91\x01\n" +
	"\x8e\x01*\x13Assign Task Request2@Data required to create and assign a new task to a staff member.\xd2\x01\bstaff_id\xd2\x01\x05title\xd2\x01\n" +
	"start_time\xd2\x01\bend_time\xd2\x01\tstatus_id\"\xdf\x01\n" +
	"\x14TrackWorkloadRequest\x12e\n" +
	"\bstaff_id\x18\x01 \x01(\tBJ\x92AG2\x1dThe UUID of the staff member.J&\"s1a2b3c4-e5f6-7890-1234-567890abcdef\"R\astaffId:`\x92A]\n" +
	"[*\x16Track Workload Request2ASpecifies the ID of the staff member whose workload is requested.\"\xe0\x01\n" +
	"\x15TrackWorkloadResponse\x12e\n" +
	"\bworkload\x18\x01 \x03(\v2\x17.staffservice.TaskProtoB0\x92A-2+List of tasks assigned to the staff member.R\bworkload:`\x92A]\n" +
	"[*\x17Track Workload Response2@Contains a list of tasks assigned to the specified staff member.\"\xdd\x01\n" +
	"\x10ListTasksRequest\x12b\n" +
	"\tstatus_id\x18\x01 \x01(\tBE\x92AB25Optional: Filter by task status ID (e.g., \"Pending\").J\t\"Pending\"R\bstatusId:e\x92Ab\n" +
	"`*\x12List Tasks Request2JRequest to list all tasks (add pagination/filtering parameters if needed).\"\x8f\x01\n" +
	"\x11ListTasksResponse\x12-\n" +
	"\x05tasks\x18\x01 \x03(\v2\x17.staffservice.TaskProtoR\x05tasks:K\x92AH\n" +
	"F*\x13List Tasks Response2/Contains a list of tasks matching the criteria.\"\xfe\x01\n" +
	"\x13AddStaffRoleRequest\x12D\n" +
	"\x04name\x18\x01 \x01(\tB0\x92A-2\x1dUnique name for the new role.J\f\"Pharmacist\"R\x04name\x12V\n" +
	"\vdescription\x18\x02 \x01(\tB4\x92A12\x15Optional description.J\x18\"Dispenses medications.\"R\vdescription:I\x92AF\n" +
	"D*\x16Add Staff Role Request2#Data for creating a new staff role.\xd2\x01\x04name\"\x9f\x01\n" +
	"\x14AddStaffRoleResponse\x120\n" +
	"\x04role\x18\x01 \x01(\v2\x1c.staffservice.StaffRoleProtoR\x04role:U\x92AR\n" +
	"P*\x17Add Staff Role Response25Contains the details of the newly created staff role.\"~\n" +
	"\x15ListStaffRolesRequest:e\x92Ab\n" +
	"`*\x18List Staff Roles Request2DRequest to list all available staff roles (no parameters currently).\"\x94\x01\n" +
	"\x16ListStaffRolesResponse\x122\n" +
	"\x05roles\x18\x01 \x03(\v2\x1c.staffservice.StaffRoleProtoR\x05roles:F\x92AC\n" +
	"A*\x19List Staff Roles Response2$A list of all available staff roles.\"\x8c\x02\n" +
	"\x15AddStaffStatusRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\tB2\x92A/2\x1fUnique name for the new status.J\f\"Terminated\"R\x04name\x12Q\n" +
	"\vdescription\x18\x02 \x01(\tB/\x92A,2\x15Optional description.J\x13\"Employment ended.\"R\vdescription:X\x92AU\n" +
	"S*\x18Add Staff Status Request20Data for creating a new staff employment status.\xd2\x01\x04name\"\xab\x01\n" +
	"\x16AddStaffStatusResponse\x126\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.staffservice.StaffStatusProtoR\x06status:Y\x92AV\n" +
	"T*\x19Add Staff Status Response27Contains the details of the newly created staff status.\"\x87\x01\n" +
	"\x18ListStaffStatusesRequest:k\x92Ah\n" +
	"f*\x1bList Staff Statuses Request2GRequest to list all available staff statuses (no parameters currently).\"\xa5\x01\n" +
	"\x19ListStaffStatusesResponse\x12:\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1e.staffservice.StaffStatusProtoR\bstatuses:L\x92AI\n" +
	"G*\x1cList Staff Statuses Response2'A list of all available staff statuses.\"\x9a\x02\n" +
	"\x14AddTaskStatusRequest\x12H\n" +
	"\x04name\x18\x01 \x01(\tB4\x92A12$Unique name for the new task status.J\t\"Blocked\"R\x04name\x12k\n" +
	"\vdescription\x18\x02 \x01(\tBI\x92AF2\x15Optional description.J-\"Task cannot proceed due to external factor.\"R\vdescription:K\x92AH\n" +
	"F*\x17Add Task Status Request2$Data for creating a new task status.\xd2\x01\x04name\"\xa7\x01\n" +
	"\x15AddTaskStatusResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.staffservice.TaskStatusProtoR\x06status:W\x92AT\n" +
	"R*\x18Add Task Status Response26Contains the details of the newly created task status.\"\x84\x01\n" +
	"\x17ListTaskStatusesRequest:i\x92Af\n" +
	"d*\x1aList Task Statuses Request2FRequest to list all available task statuses (no parameters currently).\"\xa1\x01\n" +
	"\x18ListTaskStatusesResponse\x129\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1d.staffservice.TaskStatusProtoR\bstatuses:J\x92AG\n" +
	"E*\x1bList Task Statuses Response2&A list of all available task statuses.2\xa2\x1c\n" +
	"\fStaffService\x12\xa7\x01\n" +
	"\bAddStaff\x12\x1d.staffservice.AddStaffRequest\x1a\x1e.staffservice.AddStaffResponse\"\\\x92AA\n" +
	"\x05Staff\x12\x10Add Staff Member\x1a&Adds a new staff member to the system.\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/staff\x12\xf4\x01\n" +
	"\x0fGetStaffDetails\x12$.staffservice.GetStaffDetailsRequest\x1a%.staffservice.GetStaffDetailsResponse\"\x93\x01\x92Ap\n" +
	"\x05Staff\x12\x11Get Staff Details\x1aTRetrieves details for a specific staff member by their ID, including schedule/tasks.\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/staff/{staff_id}\x12\xc4\x01\n" +
	"\tListStaff\x12\x1e.staffservice.ListStaffRequest\x1a\x1f.staffservice.ListStaffResponse\"v\x92A^\n" +
	"\x05Staff\x12\n" +
	"List Staff\x1aIRetrieves a list of staff members, optionally filtered by role or status.\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/staff\x12\xe4\x01\n" +
	"\x12UpdateStaffDetails\x12'.staffservice.UpdateStaffDetailsRequest\x1a(.staffservice.UpdateStaffDetailsResponse\"{\x92AU\n" +
	"\x05Staff\x12\x14Update Staff Details\x1a6Updates specific details for an existing staff member.\x82\xd3\xe4\x93\x02\x1d:\x01*2\x18/api/v1/staff/{staff_id}\x12\xe8\x01\n" +
	"\x13UpdateStaffSchedule\x12(.staffservice.UpdateStaffScheduleRequest\x1a\x16.google.protobuf.Empty\"\x8e\x01\x92A_\n" +
	"\x0eStaff Schedule\x12\x15Update Staff Schedule\x1a6Adds a list of new tasks to a staff member's schedule.\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/v1/staff/{staff_id}/schedule\x12\xd1\x01\n" +
	"\x14SetStaffAvailability\x12).staffservice.SetStaffAvailabilityRequest\x1a\x16.google.protobuf.Empty\"v\x92AI\n" +
	"\x05Staff\x12\x10Set Staff Status\x1a.Sets the employment status for a staff member.\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/v1/staff/{staff_id}/status\x12\xa7\x02\n" +
	"\x15GetDoctorAvailability\x12*.staffservice.GetDoctorAvailabilityRequest\x1a+.staffservice.GetDoctorAvailabilityResponse\"\xb4\x01\x92A\x8c\x01\n" +
	"\x0eStaff Schedule\n" +
	"\aDoctors\x12\x17Get Doctor Availability\x1aXRetrieves available time slots for a specific doctor or all doctors within a time range.\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/doctors/availability\x12\xca\x01\n" +
	"\n" +
	"AssignTask\x12\x1f.staffservice.AssignTaskRequest\x1a\x16.google.protobuf.Empty\"\x82\x01\x92AV\n" +
	"\vStaff Tasks\x12\vAssign Task\x1a:Creates and assigns a new task to a specific staff member.\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/staff/{staff_id}/tasks\x12\xec\x01\n" +
	"\rTrackWorkload\x12\".staffservice.TrackWorkloadRequest\x1a#.staffservice.TrackWorkloadResponse\"\x91\x01\x92Ae\n" +
	"\vStaff Tasks\x12\x14Track Staff Workload\x1a@Retrieves the list of tasks assigned to a specific staff member.\x82\xd3\xe4\x93\x02#\x12!/api/v1/staff/{staff_id}/workload\x12\xc0\x01\n" +
	"\tListTasks\x12\x1e.staffservice.ListTasksRequest\x1a\x1f.staffservice.ListTasksResponse\"r\x92AZ\n" +
	"\x05Tasks\x12\x0eList All Tasks\x1aARetrieves a list of all tasks in the system, optionally filtered.\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/tasks\x12\xc4\x01\n" +
	"\fAddStaffRole\x12!.staffservice.AddStaffRoleRequest\x1a\".staffservice.AddStaffRoleResponse\"m\x92AL\n" +
	"\aLookups\n" +
	"\vStaff Roles\x12\x0eAdd Staff Role\x1a$Creates a new staff role definition.\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/staff-roles\x12\xd3\x01\n" +
	"\x0eListStaffRoles\x12#.staffservice.ListStaffRolesRequest\x1a$.staffservice.ListStaffRolesResponse\"v\x92AX\n" +
	"\aLookups\n" +
	"\vStaff Roles\x12\x10List Staff Roles\x1a.Retrieves a list of all available staff roles.\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/staff-roles\x12\xe0\x01\n" +
	"\x0eAddStaffStatus\x12#.staffservice.AddStaffStatusRequest\x1a$.staffservice.AddStaffStatusResponse\"\x82\x01\x92A^\n" +
	"\aLookups\n" +
	"\x0eStaff Statuses\x12\x10Add Staff Status\x1a1Creates a new staff employment status definition.\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/staff-statuses\x12\xf4\x01\n" +
	"\x11ListStaffStatuses\x12&.staffservice.ListStaffStatusesRequest\x1a'.staffservice.ListStaffStatusesResponse\"\x8d\x01\x92Al\n" +
	"\aLookups\n" +
	"\x0eStaff Statuses\x12\x13List Staff Statuses\x1a<Retrieves a list of all available staff employment statuses.\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/staff-statuses\x12\xcd\x01\n" +
	"\rAddTaskStatus\x12\".staffservice.AddTaskStatusRequest\x1a#.staffservice.AddTaskStatusResponse\"s\x92AP\n" +
	"\aLookups\n" +
	"\rTask Statuses\x12\x0fAdd Task Status\x1a%Creates a new task status definition.\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/task-statuses\x12\xe1\x01\n" +
	"\x10ListTaskStatuses\x12%.staffservice.ListTaskStatusesRequest\x1a&.staffservice.ListTaskStatusesResponse\"~\x92A^\n" +
	"\aLookups\n" +
	"\rTask Statuses\x12\x12List Task Statuses\x1a0Retrieves a list of all available task statuses.\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/task-statuses\x1a0\x92A-\x12+Manage hospital staff, schedules, and tasksB\xcb\x01\x92A\x91\x01\x12g\n" +
	"\x11Staff Service API\x12MAPI for managing hospital staff, their roles, statuses, schedules, and tasks.2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ4golang-microservices-boilerplate/proto/staff-serviceb\x06proto3"

var (
	file_proto_staff_service_staff_proto_rawDescOnce sync.Once
	file_proto_staff_service_staff_proto_rawDescData []byte
)

func file_proto_staff_service_staff_proto_rawDescGZIP() []byte {
	file_proto_staff_service_staff_proto_rawDescOnce.Do(func() {
		file_proto_staff_service_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_staff_service_staff_proto_rawDesc), len(file_proto_staff_service_staff_proto_rawDesc)))
	})
	return file_proto_staff_service_staff_proto_rawDescData
}

var file_proto_staff_service_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_staff_service_staff_proto_goTypes = []any{
	(*StaffRoleProto)(nil),                         // 0: staffservice.StaffRoleProto
	(*StaffStatusProto)(nil),                       // 1: staffservice.StaffStatusProto
	(*TaskStatusProto)(nil),                        // 2: staffservice.TaskStatusProto
	(*TaskProto)(nil),                              // 3: staffservice.TaskProto
	(*ScheduleEntryProto)(nil),                     // 4: staffservice.ScheduleEntryProto
	(*Staff)(nil),                                  // 5: staffservice.Staff
	(*AddStaffRequest)(nil),                        // 6: staffservice.AddStaffRequest
	(*AddStaffResponse)(nil),                       // 7: staffservice.AddStaffResponse
	(*GetStaffDetailsRequest)(nil),                 // 8: staffservice.GetStaffDetailsRequest
	(*GetStaffDetailsResponse)(nil),                // 9: staffservice.GetStaffDetailsResponse
	(*UpdateStaffDetailsRequest)(nil),              // 10: staffservice.UpdateStaffDetailsRequest
	(*UpdateStaffDetailsResponse)(nil),             // 11: staffservice.UpdateStaffDetailsResponse
	(*ListStaffRequest)(nil),                       // 12: staffservice.ListStaffRequest
	(*ListStaffResponse)(nil),                      // 13: staffservice.ListStaffResponse
	(*UpdateStaffScheduleRequest)(nil),             // 14: staffservice.UpdateStaffScheduleRequest
	(*SetStaffAvailabilityRequest)(nil),            // 15: staffservice.SetStaffAvailabilityRequest
	(*GetDoctorAvailabilityRequest)(nil),           // 16: staffservice.GetDoctorAvailabilityRequest
	(*GetDoctorAvailabilityResponse)(nil),          // 17: staffservice.GetDoctorAvailabilityResponse
	(*AssignTaskRequest)(nil),                      // 18: staffservice.AssignTaskRequest
	(*TrackWorkloadRequest)(nil),                   // 19: staffservice.TrackWorkloadRequest
	(*TrackWorkloadResponse)(nil),                  // 20: staffservice.TrackWorkloadResponse
	(*ListTasksRequest)(nil),                       // 21: staffservice.ListTasksRequest
	(*ListTasksResponse)(nil),                      // 22: staffservice.ListTasksResponse
	(*AddStaffRoleRequest)(nil),                    // 23: staffservice.AddStaffRoleRequest
	(*AddStaffRoleResponse)(nil),                   // 24: staffservice.AddStaffRoleResponse
	(*ListStaffRolesRequest)(nil),                  // 25: staffservice.ListStaffRolesRequest
	(*ListStaffRolesResponse)(nil),                 // 26: staffservice.ListStaffRolesResponse
	(*AddStaffStatusRequest)(nil),                  // 27: staffservice.AddStaffStatusRequest
	(*AddStaffStatusResponse)(nil),                 // 28: staffservice.AddStaffStatusResponse
	(*ListStaffStatusesRequest)(nil),               // 29: staffservice.ListStaffStatusesRequest
	(*ListStaffStatusesResponse)(nil),              // 30: staffservice.ListStaffStatusesResponse
	(*AddTaskStatusRequest)(nil),                   // 31: staffservice.AddTaskStatusRequest
	(*AddTaskStatusResponse)(nil),                  // 32: staffservice.AddTaskStatusResponse
	(*ListTaskStatusesRequest)(nil),                // 33: staffservice.ListTaskStatusesRequest
	(*ListTaskStatusesResponse)(nil),               // 34: staffservice.ListTaskStatusesResponse
	(*GetDoctorAvailabilityResponse_TimeSlot)(nil), // 35: staffservice.GetDoctorAvailabilityResponse.TimeSlot
	(*timestamppb.Timestamp)(nil),                  // 36: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                          // 37: google.protobuf.Empty
}
var file_proto_staff_service_staff_proto_depIdxs = []int32{
	36, // 0: staffservice.TaskProto.start_time:type_name -> google.protobuf.Timestamp
	36, // 1: staffservice.TaskProto.end_time:type_name -> google.protobuf.Timestamp
	36, // 2: staffservice.TaskProto.created_at:type_name -> google.protobuf.Timestamp
	36, // 3: staffservice.TaskProto.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 4: staffservice.ScheduleEntryProto.task:type_name -> staffservice.TaskProto
	36, // 5: staffservice.Staff.date_of_birth:type_name -> google.protobuf.Timestamp
	4,  // 6: staffservice.Staff.schedule:type_name -> staffservice.ScheduleEntryProto
	36, // 7: staffservice.Staff.created_at:type_name -> google.protobuf.Timestamp
	36, // 8: staffservice.Staff.updated_at:type_name -> google.protobuf.Timestamp
	36, // 9: staffservice.AddStaffRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	5,  // 10: staffservice.AddStaffResponse.staff:type_name -> staffservice.Staff
	5,  // 11: staffservice.GetStaffDetailsResponse.staff:type_name -> staffservice.Staff
	36, // 12: staffservice.UpdateStaffDetailsRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	5,  // 13: staffservice.UpdateStaffDetailsResponse.staff:type_name -> staffservice.Staff
	5,  // 14: staffservice.ListStaffResponse.staff_members:type_name -> staffservice.Staff
	3,  // 15: staffservice.UpdateStaffScheduleRequest.tasks_to_schedule:type_name -> staffservice.TaskProto
	36, // 16: staffservice.GetDoctorAvailabilityRequest.start_time:type_name -> google.protobuf.Timestamp
	36, // 17: staffservice.GetDoctorAvailabilityRequest.end_time:type_name -> google.protobuf.Timestamp
	35, // 18: staffservice.GetDoctorAvailabilityResponse.available_slots:type_name -> staffservice.GetDoctorAvailabilityResponse.TimeSlot
	36, // 19: staffservice.AssignTaskRequest.start_time:type_name -> google.protobuf.Timestamp
	36, // 20: staffservice.AssignTaskRequest.end_time:type_name -> google.protobuf.Timestamp
	3,  // 21: staffservice.TrackWorkloadResponse.workload:type_name -> staffservice.TaskProto
	3,  // 22: staffservice.ListTasksResponse.tasks:type_name -> staffservice.TaskProto
	0,  // 23: staffservice.AddStaffRoleResponse.role:type_name -> staffservice.StaffRoleProto
	0,  // 24: staffservice.ListStaffRolesResponse.roles:type_name -> staffservice.StaffRoleProto
	1,  // 25: staffservice.AddStaffStatusResponse.status:type_name -> staffservice.StaffStatusProto
	1,  // 26: staffservice.ListStaffStatusesResponse.statuses:type_name -> staffservice.StaffStatusProto
	2,  // 27: staffservice.AddTaskStatusResponse.status:type_name -> staffservice.TaskStatusProto
	2,  // 28: staffservice.ListTaskStatusesResponse.statuses:type_name -> staffservice.TaskStatusProto
	36, // 29: staffservice.GetDoctorAvailabilityResponse.TimeSlot.start_time:type_name -> google.protobuf.Timestamp
	36, // 30: staffservice.GetDoctorAvailabilityResponse.TimeSlot.end_time:type_name -> google.protobuf.Timestamp
	6,  // 31: staffservice.StaffService.AddStaff:input_type -> staffservice.AddStaffRequest
	8,  // 32: staffservice.StaffService.GetStaffDetails:input_type -> staffservice.GetStaffDetailsRequest
	12, // 33: staffservice.StaffService.ListStaff:input_type -> staffservice.ListStaffRequest
	10, // 34: staffservice.StaffService.UpdateStaffDetails:input_type -> staffservice.UpdateStaffDetailsRequest
	14, // 35: staffservice.StaffService.UpdateStaffSchedule:input_type -> staffservice.UpdateStaffScheduleRequest
	15, // 36: staffservice.StaffService.SetStaffAvailability:input_type -> staffservice.SetStaffAvailabilityRequest
	16, // 37: staffservice.StaffService.GetDoctorAvailability:input_type -> staffservice.GetDoctorAvailabilityRequest
	18, // 38: staffservice.StaffService.AssignTask:input_type -> staffservice.AssignTaskRequest
	19, // 39: staffservice.StaffService.TrackWorkload:input_type -> staffservice.TrackWorkloadRequest
	21, // 40: staffservice.StaffService.ListTasks:input_type -> staffservice.ListTasksRequest
	23, // 41: staffservice.StaffService.AddStaffRole:input_type -> staffservice.AddStaffRoleRequest
	25, // 42: staffservice.StaffService.ListStaffRoles:input_type -> staffservice.ListStaffRolesRequest
	27, // 43: staffservice.StaffService.AddStaffStatus:input_type -> staffservice.AddStaffStatusRequest
	29, // 44: staffservice.StaffService.ListStaffStatuses:input_type -> staffservice.ListStaffStatusesRequest
	31, // 45: staffservice.StaffService.AddTaskStatus:input_type -> staffservice.AddTaskStatusRequest
	33, // 46: staffservice.StaffService.ListTaskStatuses:input_type -> staffservice.ListTaskStatusesRequest
	7,  // 47: staffservice.StaffService.AddStaff:output_type -> staffservice.AddStaffResponse
	9,  // 48: staffservice.StaffService.GetStaffDetails:output_type -> staffservice.GetStaffDetailsResponse
	13, // 49: staffservice.StaffService.ListStaff:output_type -> staffservice.ListStaffResponse
	11, // 50: staffservice.StaffService.UpdateStaffDetails:output_type -> staffservice.UpdateStaffDetailsResponse
	37, // 51: staffservice.StaffService.UpdateStaffSchedule:output_type -> google.protobuf.Empty
	37, // 52: staffservice.StaffService.SetStaffAvailability:output_type -> google.protobuf.Empty
	17, // 53: staffservice.StaffService.GetDoctorAvailability:output_type -> staffservice.GetDoctorAvailabilityResponse
	37, // 54: staffservice.StaffService.AssignTask:output_type -> google.protobuf.Empty
	20, // 55: staffservice.StaffService.TrackWorkload:output_type -> staffservice.TrackWorkloadResponse
	22, // 56: staffservice.StaffService.ListTasks:output_type -> staffservice.ListTasksResponse
	24, // 57: staffservice.StaffService.AddStaffRole:output_type -> staffservice.AddStaffRoleResponse
	26, // 58: staffservice.StaffService.ListStaffRoles:output_type -> staffservice.ListStaffRolesResponse
	28, // 59: staffservice.StaffService.AddStaffStatus:output_type -> staffservice.AddStaffStatusResponse
	30, // 60: staffservice.StaffService.ListStaffStatuses:output_type -> staffservice.ListStaffStatusesResponse
	32, // 61: staffservice.StaffService.AddTaskStatus:output_type -> staffservice.AddTaskStatusResponse
	34, // 62: staffservice.StaffService.ListTaskStatuses:output_type -> staffservice.ListTaskStatusesResponse
	47, // [47:63] is the sub-list for method output_type
	31, // [31:47] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_staff_service_staff_proto_init() }
func file_proto_staff_service_staff_proto_init() {
	if File_proto_staff_service_staff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_staff_service_staff_proto_rawDesc), len(file_proto_staff_service_staff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_staff_service_staff_proto_goTypes,
		DependencyIndexes: file_proto_staff_service_staff_proto_depIdxs,
		MessageInfos:      file_proto_staff_service_staff_proto_msgTypes,
	}.Build()
	File_proto_staff_service_staff_proto = out.File
	file_proto_staff_service_staff_proto_goTypes = nil
	file_proto_staff_service_staff_proto_depIdxs = nil
}
